spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pm2?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # druid 连接池管理
    druid:
      filter:
        stat:
          enabled: true
      # 配置默认的监控统计拦截的Filter
      # 不配置则监控页面中的SQL无法统计
      # stat - SQL监控配置
      # wall - SQL防火墙配置
      # slf4j - Druid日志配置
      filters: stat,wall,slf4j
      # 初始化连接池大小
      initial-size: 5
      # 连接池最大连接数
      max-active: 20
      # 每个连接上PSCache的最大值
      # 如果大于0，pool-prepared-statements自动开启
      max-pool-prepared-statement-per-connection-size: -1
      # 连接时最大等待时间（单位：毫秒）
      max-wait: 60000
      # 保持空闲连接不被关闭的最小生存时间（单位：毫秒）
      min-evictable-idle-time-millis: 300000
      # 连接池最小空闲数
      min-idle: 5
      # 是否开启PSCache，即是否缓存preparedStatement（提升写入、查询效率）
      # 建议在支持游标的数据库开启，例如：Oracle
      pool-prepared-statements: false
      # 检测获取连接时的有效性
      # 开启后会影响性能
      test-on-borrow: false
      # 检测归还连接时的有效性
      # 开启后会影响性能
      test-on-return: false
      # 检测空闲连接
      # 不影响性能，建议开启
      test-while-idle: true
      # 检测关闭空闲连接的时间间隔（单位：毫秒）
      time-between-eviction-runs-millis: 60000
      # 检测连接有效的SQL
      # 为空则test-while-idle、test-on-borrow、test-on-return配置失效
      validation-query: SELECT 1
      # 检测连接是否有效的超时时间
      validation-query-timeout: 1
      stat-view-servlet:
        # 访问白名单
        allow: 127.0.0.1
        # 配置统计页面
        enabled: true
        # 访问密码
        login-password: yuesheng
        # 访问用户名
        login-username: yuesheng
        # 允许重置监控数据
        reset-enable: true
      web-stat-filter:
        # 配置统计页面过滤
        enabled: true
        # 排除路径
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 开启session统计
        session-stat-enable: true
        # session统计的最大个数
        session-stat-max-count: 100
        # 过滤路径
        url-pattern: /*
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
      lettuce:
        pool:
          max-active: 200  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 2     # 最小空闲连接，默认0

Assets:
  #  ftp下载资源存放目录
  FTPFolder: assets/
Email:
  #  email通知信息编码
  ENCODING: UTF-8
  #  email用户名
  userName: yueshengkeji@189.cn
  #  email服务器地址
  hostName: smtp.189.com
  #  email发送端密码
  passwd:
  #    email发送端别名
  nice: pm
  #  email临时目录名称
  folder: emailApp
Notify:
  #  通知消息延迟时间（分钟）
  hour: 1
  #  发送通知使用使用服务器地址
  ip: 127.0.0.1
Article:
  #  办公用品id编码长度
  codelength: 10
System:
  #  是否debug模式运行
  debug: false
  #  关闭分布式服务器通知
  closeApproveGroup: true
  #  log路径
  log: /assets/adminex/images/logo.png
  #  默认菜单颜色
  menuBg: 424f63
  #  下载文件临时文件夹
  tempFolder: /assets/
Ftp:
  #  ftp密码
  Passwd:
  #  ftp用户名
  UserName: user_read
  #  ftp服务器地址
  Addr: 127.0.0.1
  #  ftp路径地址
  Root: /files